### PR TITLE
Fixed tests with lxml 4.7.1 or higher.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/repoze/repoze.xmliter/issues/8
We get more newlines at the end in a few cases. I simply added `strip()`.

### CODE REVIEW

**Review by tseaver — APPROVED** [review]
I would probably have kept the change for this PR more minimal (just adding the `strip()`), but this should do to get a `0.6.1` release out.

**Comment by tseaver** [comment]
LOL, turns out *I* don't have rights to push a release to PyPI.  I did just prep the release an push the [0.6.1 tag](https://github.com/repoze/repoze.xmliter/releases/tag/0.6.1).

**Comment by mauritsvanrees** [comment]
Hah, and I cannot push to this repo, but as Plone release manager, I *can* make a release on PyPI. :-) Done:
https://pypi.org/project/repoze.xmliter/0.6.1/

Thank you!

**Comment by tseaver** [comment]
I have added you to the team with write access to the repo.

**Comment by mauritsvanrees** [comment]
Thank you Tres!

**Pull request merged**
